// src/adapters/svelte/LazyScroll.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { lazyScroll } from './lazyScrollAction';

  interface Props {
    items: any[];
    itemHeight: number;
    viewportHeight: number;
    fetchMore: () => Promise<any>;
    bufferSize?: number;
  }

  export let items: any[] = [];
  export let itemHeight: number = 50;
  export let viewportHeight: number = 400;
  export let fetchMore: () => Promise<any>;
  export let bufferSize: number = 5;

  let container: HTMLElement;
  let visibleRange = $state({ start: 0, end: 0 });
  let isLoading = $state(false);

  // Initialize the lazy scroll action
  const scrollAction = (node: HTMLElement) => {
    return lazyScroll(node, {
      itemHeight,
      viewportHeight,
      bufferSize,
      fetchMore
    });
  };

  // Update visible items when visibleRange changes
  $: visibleItems = items.slice(visibleRange.start, visibleRange.end);
  $: topPadding = visibleRange.start * itemHeight;
  $: bottomPadding = Math.max(0, (items.length - visibleRange.end) * itemHeight);

  // Listen for scroll events to update visible range
  function onScroll() {
    // This will be handled by the lazyScroll action
  }

  // Refresh function
  export function refresh() {
    if (container) {
      const event = new Event('scroll');
      container.dispatchEvent(event);
    }
  }
</script>

<div
  bind:this={container}
  use:scrollAction
  class="lazy-scroll-container"
  style="height: {viewportHeight}px; overflow-y: auto;"
  on:scroll={onScroll}
>
  <!-- Top padding to maintain scroll position -->
  <div style="height: {topPadding}px;"></div>
  
  <!-- Visible items -->
  {#each visibleItems as item, index}
    <div
      style="height: {itemHeight}px;"
      class="lazy-item"
    >
      <slot {item} index={visibleRange.start + index} />
    </div>
  {/each}
  
  <!-- Bottom padding -->
  <div style="height: {bottomPadding}px;"></div>
  
  <!-- Loading indicator -->
  {#if isLoading}
    <div class="lazy-loading">
      Loading more items...
    </div>
  {/if}
</div>

<style>
  .lazy-scroll-container {
    position: relative;
  }

  .lazy-item {
    width: 100%;
  }

  .lazy-loading {
    text-align: center;
    padding: 20px;
    color: #666;
  }
</style>

// src/adapters/vue/LazyScroll.vue
<template>
  <div
    ref="containerRef"
    class="lazy-scroll-container"
    :style="{ height: `${viewportHeight}px`, overflowY: 'auto' }"
  >
    <!-- Top padding to maintain scroll position -->
    <div :style="{ height: `${topPadding}px` }"></div>
    
    <!-- Visible items -->
    <div
      v-for="(item, index) in visibleItems"
      :key="visibleRange.start + index"
      :style="{ height: `${itemHeight}px` }"
      class="lazy-item"
    >
      <slot :item="item" :index="visibleRange.start + index" />
    </div>
    
    <!-- Bottom padding -->
    <div :style="{ height: `${bottomPadding}px` }"></div>
    
    <!-- Loading indicator -->
    <div v-if="isLoading" class="lazy-loading">
      Loading more items...
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useLazyScroll } from './useLazyScroll';

// Define props
interface Props {
  items: any[];
  itemHeight: number;
  viewportHeight: number;
  fetchMore: () => Promise<any>;
  bufferSize?: number;
}

const props = withDefaults(defineProps<Props>(), {
  bufferSize: 5
});

// Use the lazy scroll composable
const { visibleRange, isLoading, containerRef, refresh } = useLazyScroll({
  itemHeight: props.itemHeight,
  viewportHeight: props.viewportHeight,
  bufferSize: props.bufferSize,
  fetchMore: props.fetchMore
});

// Calculate paddings
const topPadding = computed(() => visibleRange.value.start * props.itemHeight);
const bottomPadding = computed(() => 
  Math.max(0, (props.items.length - visibleRange.value.end) * props.itemHeight)
);

// Get visible items
const visibleItems = computed(() => 
  props.items.slice(visibleRange.value.start, visibleRange.value.end)
);

// Define slots
defineSlots<{
  default: (props: { item: any; index: number }) => void;
}>();
</script>

<style scoped>
.lazy-scroll-container {
  position: relative;
}

.lazy-item {
  width: 100%;
}

.lazy-loading {
  text-align: center;
  padding: 20px;
  color: #666;
}
</style>
