// src/adapters/angular/lazy-scroll.component.ts
import { Component, Input, Output, EventEmitter, ContentChild, TemplateRef, AfterViewInit, OnDestroy } from '@angular/core';
import { LazyScrollDirective } from './lazy-scroll.directive';

@Component({
  selector: 'lazy-scroll',
  template: `
    <div 
      class="lazy-scroll-container"
      [style.height.px]="viewportHeight"
      [style.overflow-y]="'auto'"
      [lazyScroll]="true"
      [items]="items"
      [itemHeight]="itemHeight"
      [viewportHeight]="viewportHeight"
      [bufferSize]="bufferSize"
      [fetchMore]="fetchMore"
      (visibleRangeChange)="onVisibleRangeChange($event)"
      (loadingChange)="onLoadingChange($event)"
      #scrollContainer
    >
      <!-- Top padding -->
      <div [style.height.px]="topPadding"></div>
      
      <!-- Visible items -->
      <div 
        *ngFor="let item of visibleItems; let i = index; trackBy: trackByFn" 
        [style.height.px]="itemHeight"
        class="lazy-item"
      >
        <ng-container 
          *ngTemplateOutlet="itemTemplate; context: { $implicit: item, index: visibleRange.start + i }">
        </ng-container>
      </div>
      
      <!-- Bottom padding -->
      <div [style.height.px]="bottomPadding"></div>
      
      <!-- Loading indicator -->
      <div *ngIf="isLoading" class="lazy-loading">
        Loading more items...
      </div>
    </div>
  `,
  styles: [`
    .lazy-scroll-container {
      position: relative;
    }
    
    .lazy-item {
      width: 100%;
    }
    
    .lazy-loading {
      text-align: center;
      padding: 20px;
      color: #666;
    }
  `]
})
export class LazyScrollComponent implements AfterViewInit, OnDestroy {
  @Input() items: any[] = [];
  @Input() itemHeight: number = 50;
  @Input() viewportHeight: number = 400;
  @Input() bufferSize: number = 5;
  @Input() fetchMore!: () => Promise<any>;
  
  @Output() visibleRangeChange = new EventEmitter<{ start: number; end: number }>();
  @Output() loadingChange = new EventEmitter<boolean>();
  
  @ContentChild('itemTemplate', { read: TemplateRef }) 
  itemTemplate!: TemplateRef<any>;

  visibleRange = { start: 0, end: 0 };
  isLoading = false;
  
  get topPadding(): number {
    return this.visibleRange.start * this.itemHeight;
  }
  
  get bottomPadding(): number {
    return Math.max(0, (this.items.length - this.visibleRange.end) * this.itemHeight);
  }
  
  get visibleItems(): any[] {
    return this.items.slice(this.visibleRange.start, this.visibleRange.end);
  }

  ngAfterViewInit() {
    // Component initialized
  }

  ngOnDestroy() {
    // Cleanup if needed
  }

  onVisibleRangeChange(range: { start: number; end: number }) {
    this.visibleRange = range;
    this.visibleRangeChange.emit(range);
  }

  onLoadingChange(loading: boolean) {
    this.isLoading = loading;
    this.loadingChange.emit(loading);
  }

  trackByFn(index: number, item: any): any {
    return item.id || index;
  }
}

// src/adapters/svelte/LazyScroll.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { lazyScroll } from './lazyScrollAction';

  interface Props {
    items: any[];
    itemHeight: number;
    viewportHeight: number;
    fetchMore: () => Promise<any>;
    bufferSize?: number;
  }

  export let items: any[] = [];
  export let itemHeight: number = 50;
  export let viewportHeight: number = 400;
  export let fetchMore: () => Promise<any>;
  export let bufferSize: number = 5;

  let container: HTMLElement;
  let visibleRange = $state({ start: 0, end: 0 });
  let isLoading = $state(false);

  // Initialize the lazy scroll action
  const scrollAction = (node: HTMLElement) => {
    return lazyScroll(node, {
      itemHeight,
      viewportHeight,
      bufferSize,
      fetchMore
    });
  };

  // Update visible items when visibleRange changes
  $: visibleItems = items.slice(visibleRange.start, visibleRange.end);
  $: topPadding = visibleRange.start * itemHeight;
  $: bottomPadding = Math.max(0, (items.length - visibleRange.end) * itemHeight);

  // Listen for scroll events to update visible range
  function onScroll() {
    // This will be handled by the lazyScroll action
  }

  // Refresh function
  export function refresh() {
    if (container) {
      const event = new Event('scroll');
      container.dispatchEvent(event);
    }
  }
</script>

<div
  bind:this={container}
  use:scrollAction
  class="lazy-scroll-container"
  style="height: {viewportHeight}px; overflow-y: auto;"
  on:scroll={onScroll}
>
  <!-- Top padding to maintain scroll position -->
  <div style="height: {topPadding}px;"></div>
  
  <!-- Visible items -->
  {#each visibleItems as item, index}
    <div
      style="height: {itemHeight}px;"
      class="lazy-item"
    >
      <slot {item} index={visibleRange.start + index} />
    </div>
  {/each}
  
  <!-- Bottom padding -->
  <div style="height: {bottomPadding}px;"></div>
  
  <!-- Loading indicator -->
  {#if isLoading}
    <div class="lazy-loading">
      Loading more items...
    </div>
  {/if}
</div>

<style>
  .lazy-scroll-container {
    position: relative;
  }

  .lazy-item {
    width: 100%;
  }

  .lazy-loading {
    text-align: center;
    padding: 20px;
    color: #666;
  }
</style>
